### ISSUE TITLE
Alguns bugs.

### ISSUE THREAD

**Issue by eduardolmedeiros** [eduardolmedeiros/webctl#1]
- Adequar função de status para trabalhar com a flag service-type.
- Adicionar exception para interrupção inesperada (ex: ctrl+c)

**Comment by fabiomatavelli** [comment]
Adicionada checagem da flag service-type na função status onde só executa a função se o service-type for http, caso contrário retorna erro. Além disso, foi removido o parâmetro -port do programa, já que não existe necessidade de checagem de porta por parâmetro.

Foi adicionado o tratamento da exceção de interrupção forçada do programa (Ctrl+C).

**Comment by fabiomatavelli** [comment]
Todos as checagens foram adicionadas diretamente à função status.
